version: '3'

services:
  app:
    depends_on:
      - db
    container_name: lla
    image: alderickrios/limpiaduria_linea_azul:2.0.1
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      HOST_BD: ${HOST_BD}
      PORT_BD: ${PORT_BD}
      USER_BD: ${USER_BD}
      PASSWORD_BD: ${PASSWORD_BD}
      BD_NAME: ${BD_NAME}
    restart: always

  db:
    container_name: ${BD_NAME}
    ports:
      - "5432:5432"
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_BD}
      POSTGRES_DB: ${BD_NAME}
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data

